<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>XWing.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\XWing.Sim\XWing.Sim.csproj" />
  </ItemGroup>
</Project>
